SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS mechka;
CREATE DATABASE mechka;
USE mechka;

DROP TABLE IF EXISTS recipe;
CREATE TABLE recipe (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  descriptions VARCHAR(255) NOT NULL,
  instructions TEXT NOT NULL,
  global_time VARCHAR(50) NOT NULL,
  number_persons INT NOT NULL,
  image_url VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS ingredient;
CREATE TABLE ingredient (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS recipe_ingredient;
CREATE TABLE recipe_ingredient (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  quantity INT,
  unit VARCHAR(50),
  ingredient_id INT,
  recipe_id INT,
  CONSTRAINT ingredient_id FOREIGN KEY (ingredient_id) REFERENCES ingredient(id),
  CONSTRAINT recipe_id FOREIGN KEY (recipe_id) REFERENCES recipe(id)
);

INSERT INTO recipe (title, descriptions, instructions, global_time, number_persons, image_url)
VALUES
  ('Pâtes à la Carbonara', "Une délicieuse recette de pâtes à la carbonara.", "1.Faites cuire les spaghetti dans de l'eau bouillante salée selon les instructions sur l'emballage. 2. Pendant ce temps, coupez le guanciale en petits morceaux et faites-le revenir dans une poêle jusqu'à ce qu'il soit croustillant. 3. Dans un bol, battez les œufs et mélangez-les avec le parmesan râpé. 4. Égouttez les pâtes cuites et ajoutez-les au guanciale dans la poêle, en mélangeant bien. 5. Retirez la poêle du feu et ajoutez le mélange d'œufs et de parmesan, en remuant rapidement pour éviter la coagulation. 6. Assaisonnez avec du poivre noir selon votre goût. Servez immédiatement.", "30 minutes", 4, "https://images.pexels.com/photos/14930758/pexels-photo-14930758.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"),
  ('Spaghetti Bolognaise', "Découvrez l'authenticité de la cuisine italienne avec cette recette classique de spaghetti bolognaise. Une sauce riche, des pâtes al dente et une garniture de basilic frais font de ce plat un favori pour toute la famille.", "1. Dans une grande casserole, chauffer l'huile d'olive à feu moyen. 2. Ajouter l'oignon, l'ail, le céleri et les carottes. 3. Faire revenir jusqu'à ce que les légumes soient tendres. 4. Ajouter la viande hachée et cuire jusqu'à ce qu'elle soit bien dorée. 5. Verser le vin rouge et laisser mijoter jusqu'à réduction de moitié. 6. Ajouter les tomates concassées, le concentré de tomate, le bouillon de bœuf, le sel et le poivre. Bien mélanger. Réduire le feu à doux, couvrir et laisser mijoter pendant au moins 30 minutes à 1 heure, en remuant de temps en temps. 7. Pendant ce temps, faire cuire les spaghetti selon les instructions sur l'emballage. 8.Retirer la sauce du feu. Servir la sauce bolognaise sur les spaghetti cuits, garnir de feuilles de basilic frais et de parmesan râpé.", "1 heure", 4, "https://images.pexels.com/photos/5864362/pexels-photo-5864362.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"),
  ('Poulet Rôti', 'Un délicieux poulet rôti doré à la perfection, parfait pour un repas familial.', '1. Préchauffez le four à 200°C. Rincez et séchez soigneusement le poulet. 2. Assaisonnez l intérieur du poulet avec du sel et du poivre. 3. Dans un bol, mélangez le beurre ramolli, l ail haché, le thym et le paprika. 4. Étalez le mélange de beurre sur le poulet, en veillant à bien couvrir la peau. 5. Saupoudrez le poulet avec un peu plus de sel, de poivre et de paprika. 6. Placez des tranches de citron à l intérieur du poulet. 7.Placez le poulet dans un plat allant au four et enfournez-le pendant 1 heure 30 minutes. 8. Arrosez le poulet avec son jus de cuisson toutes les 30 minutes pour le garder juteux et doré. 9. Vérifiez la cuisson en piquant le poulet avec une fourchette; les jus qui s écoulent doivent être clairs. 10. Laissez reposer le poulet pendant quelques minutes avant de le découper. 11. Servez le poulet rôti avec les tranches de citron et les jus de cuisson.', '1 heure 50 minutes', 4, 'https://images.pexels.com/photos/5718015/pexels-photo-5718015.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
  ('Saumon Grillé avec Légumes', 'Un plat sain et délicieux, associant le saumon grillé à une variété de légumes colorés.', '1. Préchauffez le grill ou le four à 200°C. 2. Dans un bol, mélangez l huile d&apos;olive, le jus de citron, l&apos;ail haché, les herbes de Provence, le sel et le poivre pour créer une marinade. 3. Placez les filets de saumon dans un plat et versez la moitié de la marinade sur le saumon. Laissez mariner pendant 10 minutes. 4. Pendant ce temps, préparez les légumes en les plaçant dans un autre plat. Versez le reste de la marinade sur les légumes et mélangez bien. 5. "Placez les filets de saumon et les légumes sur le grill ou dans le four. Faites cuire pendant environ 15-20 minutes ou jusqu&apos;à ce que le saumon soit cuit et les légumes soient tendres. 6. Servez le saumon grillé sur un lit de légumes et arrosez avec le jus de cuisson. 7. Garnissez avec des quartiers de citron frais.', '35 minutes', 2, 'https://images.pexels.com/photos/3763847/pexels-photo-3763847.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
  ('Risotto aux Champignons', 'Un délicieux risotto crémeux avec une saveur riche de champignons sautés.', '1. Dans une poêle, faites chauffer l&apos;huile d&apos;olive. 2. Ajoutez l&apos;oignon et l&apos;ail, faites-les revenir jusqu&apos;à ce qu&apos;ils soient translucides. 3. Ajoutez les champignons et faites-les sauter jusqu&apos;à ce qu&apos;ils soient dorés. Réservez quelques champignons pour la garniture. 4. Ajoutez le riz Arborio dans la poêle et mélangez bien pour enrober de matière grasse. 5. Versez le vin blanc sec dans la poêle et remuez jusqu&apos;à absorption. 6. Commencez à ajouter le bouillon de légumes, une louche à la fois, en remuant fréquemment. Attendez que le liquide soit absorbé avant d&apos;ajouter la suivante. 7. Continuez jusqu&apos;à ce que le riz soit cuit al dente et ait une consistance crémeuse (environ 18-20 minutes). 8. Incorporez le beurre et le parmesan râpé. Assaisonnez avec du sel et du poivre selon votre goût. 9. Servez le risotto aux champignons dans des assiettes, garnissez avec les champignons réservés et saupoudrez de persil frais haché.', '35 minutes', 4, 'https://images.pexels.com/photos/5638527/pexels-photo-5638527.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
  ('Crumble aux Pommes', 'Un dessert délicieusement croustillant avec des pommes tendres et une couche de crumble parfumée à la cannelle.', '1. Préchauffez le four à 180°C. 2. Dans un grand bol, mélangez les tranches de pommes avec le sucre, la cannelle et le jus de citron. Répartissez les pommes dans un plat de cuisson beurré. 3. Dans un autre bol, mélangez la farine, le sucre brun, les flocons d&apos;avoine, le beurre et le sel. Mélangez avec les doigts jusqu&apos;à l&apos;obtention d&apos;une texture granuleuse. 4. Si désiré, ajoutez les noix hachées au mélange de crumble. 5. Saupoudrez le mélange de crumble sur les pommes dans le plat de cuisson, en veillant à couvrir uniformément. 6. Faites cuire au four pendant environ 30 minutes ou jusqu&apos;à ce que le dessus soit doré et que les pommes soient tendres. 7. Laissez refroidir légèrement avant de servir. Vous pouvez accompagner le crumble d&apos;une boule de glace à la vanille pour un délice supplémentaire.', '45 minutes', 6, 'https://images.pexels.com/photos/18403952/pexels-photo-18403952/free-photo-of-pain-nourriture-assiette-bois.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
  ('Cookies aux Pépites de Chocolat', 'Des cookies moelleux à l&apos;intérieur et croustillants à l&apos;extérieur, pleins de pépites de chocolat fondantes.', '1. Préchauffez le four à 180°C. 2. Dans un grand bol, battez le beurre ramolli, le sucre brun et le sucre blanc jusqu&apos;à obtention d&apos;un mélange crémeux. 3. Ajoutez l&apos;œuf et l&apos;extrait de vanille, et mélangez bien. 4. Dans un autre bol, mélangez la farine, la levure chimique et le sel. Ajoutez ce mélange sec à la préparation humide et mélangez jusqu&apos;à obtenir une pâte homogène. 5. Incorporez les pépites de chocolat (et les noix hachées si vous le souhaitez) à la pâte. 6. Sur une plaque de cuisson recouverte de papier sulfurisé, déposez des cuillerées de pâte, en les espaçant pour permettre l&apos;expansion pendant la cuisson. 7. Faites cuire au four pendant environ 10 minutes ou jusqu&apos;à ce que les bords des cookies soient légèrement dorés. 8. Laissez refroidir les cookies sur la plaque pendant quelques minutes avant de les transférer sur une grille pour les laisser refroidir complètement.', '25 minutes', 12, 'https://images.pexels.com/photos/2067424/pexels-photo-2067424.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
  ('Lasagnes Bolognaises', 'Un plat italien classique avec des couches de pâtes, une sauce bolognaise savoureuse, béchamel et fromage fondant.', ' 1. Préchauffez le four à 180°C. 2. Dans une casserole, faites revenir l&apos;oignon et l&apos;ail dans un peu d&apos;huile d&apos;olive jusqu&apos;à ce qu&apos;ils soient tendres. 3. Ajoutez la viande de bœuf hachée et faites-la cuire jusqu&apos;à ce qu&apos;elle soit bien dorée. Égouttez l&apos;excès de graisse. 4. Ajoutez les tomates concassées, le concentré de tomate, le vin rouge, le bouillon de bœuf, le thym, les feuilles de laurier, le sel et le poivre. Laissez mijoter pendant 20 minutes. 5. Pendant ce temps, préparez la béchamel. Dans une casserole, faites fondre le beurre, ajoutez la farine et remuez pendant quelques minutes. Ajoutez le lait progressivement en remuant constamment jusqu&apos;à ce que la sauce épaississe. Ajoutez la noix de muscade et retirez du feu. 6. Dans un plat allant au four, alternez les couches de feuilles de lasagne, de sauce bolognaise et de béchamel. Répétez jusqu&apos;à épuisement des ingrédients, en terminant par une couche de béchamel. Saupoudrez de fromage râpé sur le dessus. 7. Faites cuire au four pendant environ 30-40 minutes, jusqu&apos;à ce que le dessus soit doré et les lasagnes bien cuites. 8. Laissez reposer quelques minutes avant de servir. Bon appétit !', '1 heure et 10 minutes', 6, 'https://images.pexels.com/photos/14696209/pexels-photo-14696209.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2');

  INSERT INTO ingredient (name) 
VALUES 
    ('Pâtes'),
    ('Lardons fumés'),
    ('Œufs'),
    ('Parmesan râpé'),
    ('Poivre noir'),
    ('Sel'),
    ('Pâtes'),
    ('Viande hachée'),
    ('Oignon'),
    ('Ail'),
    ('Carottes'),
    ('Céleri'),
    ('Tomates concassées en conserve'),
    ('Concentré de tomate'),
    ('Vin rouge'),
    ('Bouillon de bœuf'),
    ('Feuilles de basilic frais'),
    ('Parmesan râpé'),
    ('Huile Olive'),
    ('Sel'),
    ('Poive noir'),
    ("Poulet entier"),
    ("Sel"),
    ("Poivre"),
    ("Paprika"),
    ("Beurre"),
    ("Ail"),
    ("Thym"),
    ("Citron"),
    ("Filets de saumon"),
    ("Courgette"),
    ("Poivron rouge"),
    ("Tomates cerises"),
    ("Huile d'olive"),
    ("Citron"),
    ("Ail"),
    ("Herbes de Provence"),
    ("Sel"),
    ("Poivre"),
    ("Riz Arborio"),
    ("Champignons de Paris"),
    ("Oignon"),
    ("Ail"),
    ("Vin blanc sec"),
    ("Bouillon de légumes"),
    ("Parmesan râpé"),
    ("Beurre"),
    ("Huile d'olive"),
    ("Sel"),
    ("Poivre"),
    ("Persil frais"),
    ("Pommes"),
    ("Sucre"),
    ("Cannelle"),
    ("Jus de citron"),
    ("Farine"),
    ("Sucre brun"),
    ("Flocons d'avoine"),
    ("Beurre"),
    ("Sel"),
    ("Noix"),
    ("Beurre"),
    ("Sucre brun"),
    ("Sucre blanc"),
    ("Œuf"),
    ("Extrait de vanille"),
    ("Farine tout usage"),
    ("Levure chimique"),
    ("Sel"),
    ("Pépites de chocolat"),
    ("Noix hachées"),
    ("Feuilles de lasagne"),
    ("Viande de bœuf hachée"),
    ("Oignon"),
    ("Ail"),
    ("Tomates concassées en conserve"),
    ("Concentré de tomate"),
    ("Vin rouge"),
    ("Bouillon de bœuf"),
    ("Thym séché"),
    ("Feuilles de laurier"),
    ("Sel"),
    ("Poivre"),
    ("Beurre"),
    ("Farine"),
    ("Lait"),
    ("Noix de muscade"),
    ("Fromage râpé");

INSERT INTO Recipe_Ingredient (quantity, unit, ingredient_id, recipe_id)
VALUES 
	(400, 'Grammes', 1, 1),
    (200, 'Grammes', 2, 1),
    (4,'', 3, 1),
    (150, 'Grammes', 4, 1),
    (0.5, 'Cuillère à café', 5, 1),
    (1, 'Pincée', 6, 1),
    (400, 'Grammes', 7, 2),
    (500, 'Grammes', 8, 2),
    (1, 'Moyen', 9, 2),
    (3, 'Gousses', 10, 2),
    (2, 'moyennes rapées', 11, 2),
    (1, 'Branche', 12, 2),
    (800, 'Grammes', 13, 2), 
    (2, 'Cuillères à soupe', 14, 2),
    (1, 'Tasse', 15, 2),
    (1, 'Tasse', 16, 2),
    (1, 'À convenance', 17, 2),
    (1, 'Pour garnir', 18, 2),
    (2, 'Cuillères à soupe', 19, 2),
    (1, 'Selon le goût', 20, 2),
    (1, 'Selon le goût', 21, 2),
    (1, 'Poulet entier', 22, 3),
    (1, 'Cuillère à soupe de sel', 23, 3),
    (1, "Cuillère à café de poivre", 24, 3),
    (1, "Cuillère à café de paprika", 25, 3),
    (50, "Grammes", 26, 3),
    (3, "Gousses", 27, 3),
    (1, "Brin", 28, 3),
    (1, "", 29, 3),
    (2, "Filets", 30, 4),
    (1, "", 31, 4),
    (1, "", 32, 4),
    (1, "Tasse", 33, 4),
    (2, "Cuillères à soupe", 34, 4),
    (1, "Jus", 35, 4),
    (2, "Gousses hachées", 36, 4),
    (1, "Cuillère à café", 37, 4),
    (0.5, "Cuillère à café", 38, 4),
    (0.25, "Cuillère à café", 39, 4),
    (1, "Tasse de Riz Arborio", 40, 5),
    (250, "Grammes (coupés en tranches)", 41, 5),
    (1, "Oignon (finement haché)", 42, 5),
    (2, "Gousses(hachées)", 43, 5),
    (0.5, "Tasse", 44, 5),
    (4, "Tasses de Bouillon de légumes (chaud)", 45, 5),
    (0.5, "Tasse de Parmesan râpé", 46, 5),
    (2, "Cuillères à soupe de Beurre", 47, 5),
    (2, "Cuillères à soupe", 48, 5),
    (0.5, "Cuillère à café", 49, 5),
    (0.25, "Cuillère à café", 50, 5),
    (2, "Cuillères à soupe", 51, 5),
    (4, '', 52, 6),
    (0.5, "Tasse", 53, 6),
    (1, "Cuillère", 54, 6),
    (1, "Cuillère à soupe", 55, 6),
    (1, "Tasse", 56, 6),
    (0.5, "Tasse", 57, 6),
    (0.5, "Tasse", 58, 6),
    (0.5, "Tasse", 59, 6),
    (0.25, "Cuillère à café", 60, 6),
    (0.5, "Tasse", 61, 6),
    (0.5, "Tasse", 62, 7),
    (0.5, "Tasse", 63, 7),
    (0.25, "Tasse", 64, 7),
    (1, "", 65, 7),
    (1, "Cuillère à café", 66, 7),
    (0.25, "Tasse", 67, 7),
    (0.5, "Cuillère à café", 68, 7),
    (0.25, "Cuillère à café", 69, 7),
    (1, "Tasse", 70, 7),
    (0.5, "Tasse",  71, 7),
    (250, "Grammes de Feuilles", 72,8), 
    (500, "Grammes", 73,8), 
    (1, "(haché)", 74,8), 
    (3, "Gousses (hachées)", 75,8), 
    (800, "Grammes", 76,8), 
    (2, "Cuillères à soupe", 77,8), 
    (0.5, "Tasse", 78,8), 
    (1, "Tasse", 79,8), 
    (1, "Cuillère à café", 80,8), 
    (2, "Feuilles", 81,8), 
    (0.5, "Cuillère à café", 82,8), 
    (0.25, "Cuillère à café", 83,8), 
    (50, "Grammes", 84,8), 
    (50, "Grammes", 85,8), 
    (500, "ml", 86,8), 
    (0.25, "Cuillère à café", 87,8), 
    (200, "Grammes",  88,8);

SET FOREIGN_KEY_CHECKS = 1;